---
  - name: Create new volume ansible_data
    purefa_volume:
      name: hv4-{{ cliente }}-{{ server_id }}-vol{{ vol_id }}
      size: "{{ size }}"
      fa_url: 10.220.14.5
      api_token: 2475f960-2a79-21d0-5994-ef374bde6689
...