---
- name: DELL Bare-metal Provisioning
  hosts: pxe
  gather_facts: false
  vars:
    lock_dir: "/tmp/ansible-playbook-dell-bm-provisioning-{{  idrac_ip  }}.lock"

  pre_tasks:
    - name: wait for lock
      include_tasks: wait_for_lock.yaml
      vars:
        wait_for_lock_dir: "{{ lock_dir }}"

  roles:
    - dell-bm-provisioning

  post_tasks:
    - name: clear lock
      file:
        path: "{{ lock_dir }}"
        state: absent
      become: yes