---
- name: BIND DNS Installation
  hosts: backup_dns
  gather_facts: true
  vars:
    lock_dir: "/tmp/ansible-playbook-linux-bind.lock"
  vars_files:
    - vars/backup-bind-vars.yaml

  pre_tasks:
    - name: wait for lock
      include_tasks: wait_for_lock.yaml
      vars:
        wait_for_lock_dir: "{{ lock_dir }}"

  roles:
    - linux-bind

  post_tasks:
    - name: clear lock
      file:
        path: "{{ lock_dir }}"
        state: absent
      become: yes
