---
- name: RHEL Backup Installation
  hosts: all
  gather_facts: true
  serial: 1
  vars:
    lock_dir: "/tmp/ansible-playbook-rhel-backup-{{ inventory_hostname }}.lock"

  pre_tasks:
    - name: wait for lock
      include_tasks: wait_for_lock.yaml
      vars:
        wait_for_lock_dir: "{{ lock_dir }}"

  roles:
    - rhel-backup

  post_tasks:
    - name: clear lock
      file:
        path: "{{ lock_dir }}"
        state: absent
      become: yes
