---
- name: Lenovo Bare-metal Provisioning
  hosts: pxe
  gather_facts: false
  vars:
    lock_dir: "/tmp/ansible-playbook-lenovo-bm-provisioning-10.228.4.108.lock"
    
  #pre_tasks:
  #  - name: wait for lock
  #    include_tasks: wait_for_lock.yaml
  #    vars:
  #      wait_for_lock_dir: "{{ lock_dir }}"

  roles:
    - test_lenovo

  #post_tasks:
  #  - name: clear lock
  #    file:
  #      path: "{{ lock_dir }}"
  #      state: absent
  #    become: yes

...
