---
  - name: Creating and configuring a zone.
    hosts: all
    connection: local
    gather_facts: false
    collections:
      - paloaltonetworks.panos
    roles:
      - test_zone_config
...