---
- name: Windows Backup Agent Installation
  hosts: win
  serial: 1
  gather_facts: true
  vars:
    lock_dir: "/tmp/ansible-playbook-windows-backup-{{  inventory_hostname  }}.lock"

  pre_tasks:
    - name: wait for lock
      include_tasks: wait_for_lock.yaml
      vars:
        wait_for_lock_dir: "{{ lock_dir }}"

  roles:
    - windows-backup

  post_tasks:
    - name: clear lock
      file:
        path: "{{ lock_dir }}"
        state: absent
      become: yes