---
  - name: Create dynamic NAT rule on the firewall
    collections:
    - paloaltonetworks.panos  
    panos_nat_rule:
      provider: '{{ palo_provider }}'
      rule_name: '{{ nat_name }}'
      source_zone: '{{ source_zone }}'
      destination_zone: '{{ destination_zone }}'
      source_ip: '{{ source_ip }}'
      destination_ip: '{{ destination_ip }}'
      service: '{{ service }}'
      snat_address_type: '{{ snat_address_type }}'
      snat_type: '{{ snat_type }}'
      snat_interface: '{{ snat_interface }}'
      vsys: '{{ vsys }}'

  - name: commit candidate configs on firewall
    collections:
    - paloaltonetworks.panos  
    panos_commit_firewall:
      provider: '{{ palo_provider }}'
...
