---
- name:
  block:
     - name: Definindo primeira interface de produção
       shell: "ip addr show |grep state\\ UP |sed -n '2p' |awk '{print $2}' |sed 's/://' "
       register: if_name1
     - name:
       set_fact:
         if_name1: "{{ if_name1.stdout }}"
     - name:  
       debug:
         msg: " {{ if_name1 }} é a primeira interface de produção."

- name:
  block:
     - name: Definindo Segunda interface de produção
       shell: "ip addr show |grep state\\ UP |sed -n '3p' |awk '{print $2}' |sed 's/://' "
       register: if_name2
     - name:
       set_fact:
         if_name2: "{{ if_name2.stdout }}"
     - name:  
       debug:
         msg: " {{ if_name2 }} é a segunda interface de produção."

- name:
  block:
     - name: Criando interface lógica de bond
       shell: |
         cmd:
           nmcli con add type bond con-name bond0 ifname bond0 mode 802.3ad ip4 {{ ip_bond }} ipv4.gateway {{ gateway_bond }} connection.autoconnect yes
           nmcli con mod id bond0 802-3-ethernet.mtu 9000
           nmcli conn del {{ if_name1 }}
           nmcli conn del {{ if_name2 }}
           nmcli con add type bond-slave ifname {{ if_name1 }} con-name {{ if_name1 }} master bond0
           nmcli con add type bond-slave ifname {{ if_name2 }} con-name {{ if_name2 }} master bond0
           nmcli con up bond0
       register: out
     - name:
       debug:
         msg: "{{ out.stdout }}"
     - name: Checando bonding criado.
       shell: |
         cmd:
           nmcli con show |grep bond0
       register: out2
     - name:
       debug:
         msg: "{{ out2.stdout }}"         
         
- name: Restart service NetworManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
    
- name:
  block:
     - name: Checando bonding
       debug:
         msg: "Sucesso. O bonding bond0 foi criado com o ip {{ ip_bond }}"
     
...