---
- name: Criando Application Profile AP
  aci_ap:
    hostname: "{{ inventory_hostname }}"
    username: "{{ lookup('env','APIC_USER')}}"
    password: "{{ lookup('env','APIC_PASS')}}"
    tenant: "{{ TENANT }}-{{ VLAN }}"
    ap: "app-{{ CLIENTE | lower }}"
    description: "Default AP {{ CLIENTE }}"
    state: present
    validate_certs: no
  register: create_ap_output

- debug:
    msg: "{{ create_ap_output }}"
