---
- name: Create a subnet with options
  aci_bd_subnet:
    hostname: "{{ inventory_hostname }}"
    username: "{{ lookup('env','APIC_USER')}}"
    password: "{{ lookup('env','APIC_PASS')}}"
    tenant: "{{ TENANT }}-{{ VLAN }}"
    bd: "{{ BD }}-{{ item }}-{{ VLAN }}"
    subnet_name: "subnet-{{ CLIENTE }}-{{ item }}-{{ VLAN }}"
    gateway: "{{ lookup('vars', item + '_subnet') | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
    mask: "{{ lookup('vars', item + '_subnet') | ipaddr('prefix') }}"
    description: "{{ CLIENTE }}-{{ item }}-{{ VLAN }}"
    scope: [public, shared]
    route_profile_l3_out: L3out-TRANSITO_FG1
    state: present
    validate_certs: no
  loop: "{{ ENV }}"
  register: create_subnet_output

- debug:
    msg: "{{ create_subnet_output }}"

