---
- name: Criando tenant "{{ TENANT }}"
  aci_tenant:
    hostname: "{{ inventory_hostname }}"
    username: "{{ lookup('env','APIC_USER')}}"
    password: "{{ lookup('env','APIC_PASS')}}"
    tenant: "{{ TENANT }}-{{ VLAN }}"
    description: "Cliente: {{ CLIENTE }}"
    state: present
    validate_certs: no
  register: create_tenant_output

- debug:
    msg: "{{ TENANT }}-{{ VLAN }} criado com sucesso"
  when: create_tenant_output.changed == true and create_tenant_output.failed == false
