---
  - name: collect all information
    purefa_info:
        gather_subset:
          - hosts
        fa_url: 10.220.14.5
        api_token: 2475f960-2a79-21d0-5994-ef374bde6689
    register: array_info
  - name: retrieve info
    set_fact:
      info_hosts: "{{ array_info | json_query('purefa_info.hosts.*.wwn') | regex_replace('[^A-Z 0-9]', '') }}"
  - name: show configuration information
    set_fact: 
      info_hosts_list: "{{ info_hosts.split(' ') }}"
  - name: Output
    debug:
      msg: "É diferente isso"
    when:
    - wwn1 in item != -1
    with_items: "{{ info_hosts_list }}"
    
#when: {{ wwn1 }} and {{ wwn2 }} != {{ item }}"  
      
      
#'purefa_info.hosts.*.wwn'
