---
  - name: collect all information
    purefa_info:
        gather_subset:
          - all
        fa_url: 10.220.14.5
        api_token: 2475f960-2a79-21d0-5994-ef374bde6689
    register: array_info
  - name: show all information
    debug:
      msg: "{{ array_info['purefa_info'] }}"
...
