---
  - name: collect all information
    purefa_info:
        gather_subset:
          - "{{ subset }}"
        fa_url: 10.220.14.5
        api_token: 2475f960-2a79-21d0-5994-ef374bde6689
    register: array_info
  - name: retrieve info
    set_fact:
      info_hosts: "{{ array_info | json_query('purefa_info.hosts[*].wwn[*]') }}"
  - name: show configuration information
    debug: 
      msg: "{{ info_hosts }}"

#'purefa_info.hosts.*.wwn'
