---
  - name: collect all information
    purefa_info:
        gather_subset:
          - hosts
        fa_url: 10.220.14.5
        api_token: 2475f960-2a79-21d0-5994-ef374bde6689
    register: array_info
  - name: retrieve info
    set_fact:
      info_hosts: "{{ array_info | json_query('purefa_info.hosts.*.wwn')  | regex_replace('[^A-Z 0-9]', '') }}"
      
  - name: show configuration information
    set_fact: 
      info_hosts_list: "{{ info_hosts.split(' ') }}"
  - name: Create new host
    purefa_host:
      host: HV4-{{ cliente }}-{{ server_id }}
      protocol: fc
      wwns:
        - "{{ wwn1 }}"
        - "{{ wwn2 }}"
      volume: hv4-{{ cliente }}-{{ server_id }}-vol{{ vol_id }}
      state: present
      fa_url: 10.220.14.5
      api_token: 2475f960-2a79-21d0-5994-ef374bde6689
    when:
    - wwn1 is not in info_hosts_list
    - wwn2 is not in info_hosts_list
...
