---
  - name: add SSH inbound rule to Panorama device group
    panos_security_rule:
      provider: '{{ provider }}'
      device_group: 'Cloud Edge'
      rule_name: 'SSH permit'
      description: 'SSH rule test'
      tag_name: ['production']
      source_zone: ['public']
      source_ip: ['any']
      destination_zone: ['private']
      destination_ip: ['1.1.1.1']
      application: ['ssh']
      action: 'allow'

  - name: add a rule to allow HTTP multimedia only to CDNs
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'HTTP Multimedia'
      description: 'Allow HTTP multimedia only to host at 1.1.1.1'
      source_zone: ['private']
      destination_zone: ['public']
      category: ['content-delivery-networks']
      application: ['http-video', 'http-audio']
      service: ['service-http', 'service-https']
      action: 'allow'

  - name: add a more complex rule that uses security profiles
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'Allow HTTP'
      source_zone: ['public']
      destination_zone: ['private']
      log_start: false
      log_end: true
      action: 'allow'
      antivirus: 'strict'
      vulnerability: 'strict'
      spyware: 'strict'
      url_filtering: 'strict'
      wildfire_analysis: 'default'

  - name: disable a Panorama pre-rule
    panos_security_rule:
      provider: '{{ provider }}'
      device_group: 'Production edge'
      rule_name: 'Allow telnet'
      source_zone: ['public']
      destination_zone: ['private']
      source_ip: ['any']
      destination_ip: ['1.1.1.1']
      log_start: false
      log_end: true
      action: 'allow'
      disabled: true

  - name: delete a device group security rule
    panos_security_rule:
      provider: '{{ provider }}'
      state: 'absent'
      device_group: 'DC Firewalls'
      rule_name: 'Allow telnet'

  - name: add a rule at a specific location in the rulebase
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'SSH permit'
      description: 'SSH rule test'
      source_zone: ['untrust']
      destination_zone: ['trust']
      source_ip: ['any']
      source_user: ['any']
      destination_ip: ['1.1.1.1']
      category: ['any']
      application: ['ssh']
      service: ['application-default']
      action: 'allow'
      location: 'before'
      existing_rule: 'Allow MySQL'