---
- name: Static binding deployment for a set of interfaces in EPG
  block:
    - name: Add a new physical domain to EPG binding
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ lookup('env','APIC_USER')}}"
        password: "{{ lookup('env','APIC_PASS')}}"
        tenant: "{{ TENANT }}-{{ VLAN }}"
        ap: "{{ APP }}"
        epg: "{{ EPG }}-{{ item.0 }}-{{ VLAN }}"
        domain: nome_domain
        domain_type: phys
        state: present
        validate_certs: no

    - name: Deploy Static Path binding for given EPG
      aci_static_binding_to_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ lookup('env','APIC_USER')}}"
        password: "{{ lookup('env','APIC_PASS')}}"
        tenant: "{{ TENANT }}-{{ VLAN }}"
        ap: "{{ APP }}"
        epg: "{{ EPG }}-{{ item.0 }}-{{ VLAN }}"
        encap_id: "{{ VLAN_ID }}"
        deploy_immediacy: lazy
        interface_mode: "{{ INT_MODE }}"
        interface_type: "{{ INT_TYPE }}"
        pod_id: 1
        leafs: "{{ LEAFS }}"
        interface: "{{ INTERFACE }} "
        state: present
        validate_certs: no
