---
- name: Verifying variable definition
  fail: 
    msg: "[ERROR] One or more required variables are not defined. Please check the parameter definition before trying again."
  when: "{{ item }} is not defined"
  with_items:
    - mode

#- name: PADRONIZANDO DADOS
#  include_tasks: padronizando_vars.yaml

- include_tasks: deploy-binding.yaml
  when: mode == "bind"

- include_tasks: remove-binding.yaml
  when: mode == "remove"

- include_tasks: query-binding.yaml
  when: mode == "query"
