---
  - name: Adding a LUN to existing host
    purefa_host:
      host: HV4-{{ cliente }}-{{ server_id }}
      volume: hv4-{{ cliente }}-{{ server_id }}-vol{{ vol_id }}
      state: present
      fa_url: 10.220.14.5
      api_token: 2475f960-2a79-21d0-5994-ef374bde6689
...