---
  - name: Creating a subinterface as static in zone dmz
    collections:
    - paloaltonetworks.panos
    panos_l3_subinterface:
      provider: '{{ palo_provider }}'
      name: "ae4.30"
      tag: 30
      enable_dhcp: false
      ip: ["10.1.1.1/24"]
      zone_name: "dmz"
      vsys: vsys4

  - name: commit candidate configs on firewall
    collections:
    - paloaltonetworks.panos  
    panos_commit_firewall:
      provider: '{{ palo_provider }}'
...